language: c

# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - NimBinaries

git:
  # when multiple CI builds are queued, the tested commit needs to be in the last X commits cloned with "--depth X"
  depth: 10

matrix:
  include:
    - os: linux
      compiler: gcc
    - dist: bionic
      # Bionic to avoid git failure "fatal: unknown date format unix"
      compiler: gcc
      arch: arm64
    - dist: bionic
      arch: ppc64le
      env:
        - ARCH=powerpc64el
        - CHANNEL=devel
      compiler: gcc
    - os: osx
      compiler: clang

install:
  # build nim from our own branch - this to avoid the day-to-day churn and
  # regressions of the fast-paced Nim development while maintaining the
  # flexibility to apply patches
  - curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus-build-system/master/scripts/build_nim.sh
  - env MAKE="make -j2" V=1 bash build_nim.sh Nim csources dist/nimble NimBinaries
  - export PATH=$PWD/Nim/bin:$PATH

script:
  - nimble install -y
  # testing only
  - nimble install https://github.com/status-im/NimYAML@#head # Cannot clone upstream https://github.com/flyx/NimYAML/issues/77
  - nimble install stint

  # Temporary patch for https://github.com/supranational/blst/issues/46#issuecomment-738939501
  - pushd vendor/blst
  - git fetch https://github.com/dot-asm/blst no-asm-as-command-line
  - git cherry-pick 8e37f9e14306f39ae5417cd223112b5d20656d49
  - popd

  - nimble test
